FROM python:latest

EXPOSE 8080

RUN mkdir /usr/src/app

WORKDIR /usr/src/app

CMD ["/bin/bash"]

# FROM node

# EXPOSE 8080

# COPY ./ /app/
# WORKDIR /app

# RUN npm i 

# CMD node part3.js